version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: prod #change to prod if want run to production
      DATABASE_URL: postgres://postgres:postgres@db:5432/contaichallenge
      SECRET_KEY_BASE: 82cIseOlE4lf/pXaQ/dBaEpx6XRFlMCmjSHIqb+tLg5h0HWZutdHeEDQr0lBXxil
    env_file:
      - .env
    ports:
      - '4000:4000' #change port to listen
volumes:
  pgdata: